defaultSemverRangePrefix: "^"
nodeLinker: pnp

logFilters:
  # TODO: Remove these filters when react-use goes past 17.3.2
  - text: "trafique@workspace:. provides react (pe8962) with version 18.0.0, which doesn't satisfy what react-use and some of its descendants request"
    level: discard
  - text: "trafique@workspace:. provides react-dom (pbf4c1) with version 18.0.0, which doesn't satisfy what react-use and some of its descendants request"
    level: discard

packageExtensions:
  react-dev-utils@12.0.1:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  eslint-config-react-app@7.0.1:
    peerDependencies:
      '@babel/plugin-syntax-flow': ^7.14.5
      '@babel/plugin-transform-react-jsx': ^7.14.9
  react-scripts@5.0.1:
    peerDependencies:
      '@babel/plugin-syntax-flow': ^7.14.5
      '@babel/plugin-transform-react-jsx': ^7.14.9
      eslint-config-react-app: '^7.0.0'
      autoprefixer: ^10.0.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

pnpMode: strict
