yarnPath: ".yarn/releases/yarn-berry.cjs"

# logFilters:
  # See https://github.com/yarnpkg/yarn/issues/8052#issuecomment-735764698
  # - code: YN0032 # "Implicit dependencies on node-gyp are discouraged. 

# automatically pin dependencies on "yarn add"
defaultSemverRangePrefix: ""

packageExtensions:
  react-dev-utils@11.0.4:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
