defaultSemverRangePrefix: ""

packageExtensions:
  react-dev-utils@11.0.4:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
