# yarnPath: .yarn/releases/yarn-2.4.2.cjs
logFilters:
  # See https://github.com/yarnpkg/yarn/issues/8052#issuecomment-735764698
  - code: YN0032 # "Implicit dependencies on node-gyp are discouraged. 

# automatically pin dependencies on "yarn add"
defaultSemverRangePrefix: ""
