defaultSemverRangePrefix: "^"
nodeLinker: pnp

packageExtensions:
  react-dev-utils@12.0.0:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  eslint-config-react-app@7.0.0:
    peerDependencies:
      '@babel/plugin-syntax-flow': ^7.14.5
      '@babel/plugin-transform-react-jsx': ^7.14.9
  react-scripts@5.0.0:
    peerDependencies:
      '@babel/plugin-syntax-flow': ^7.14.5
      '@babel/plugin-transform-react-jsx': ^7.14.9
      autoprefixer: ^10.0.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

pnpMode: strict
